version: "3"
services:
  tomcat-1:
    image: "tomcat:9"
    ports:
    - "8081-8083:8080"
    volumes:
    - "/mnt/dev-wars:/usr/local/tomcat/webapps"
  tomcat-2:
    image: "tomcat:9"
    ports:
    - "8084-8085:8080"
    volumes:
    - "/mnt/qa-wars:/usr/local/tomcat/webapps"

